### ISSUE TITLE
Cloudfare Returns Recaptcha for Download

### ISSUE THREAD

**Issue by m1st0** [android-police/apkmirror-public#54] opened 2018-03-20 01:22 UTC
#### Expected behavior
Download an old APK such as for Southwest Airlines [here](https://www.apkmirror.com/apk/southwest-airlines/southwest-airlines/southwest-airlines-4-8-2-release/southwest-airlines-4-8-2-android-apk-download/) .

#### Actual behavior
Cloudfare returns a recaptcha Web page rather than the download itself.  User is unaware that the download is only a HTML.

#### Steps to reproduce the problem
Once the download finishes, if you open it in a text editor, you will see Cloudfare HTML rather than the download.  You may also change the file extension for Windows to .html in order for this to be opened in a browser but it appears blank as well due to the origin being local.

**Comment by archon810** [comment] 2018-03-20 02:04
I cannot reproduce this - the download is an apk file for me 8+MB in size.

**Comment by m1st0** [comment] 2018-03-22 02:03
Humm, my download is a lot smaller. Cloudfare is what is sending me the
wrong file by requiring a broken captcha page to prove I am human. So
something in the Cloudflare settings in the site for my connection I am
assuming. It is named correctly with an extensuon, but the size was so
small I just opened it in vim and found HTML.

**Comment by archon810** [comment] 2018-03-29 20:06
We do challenge some overly active scrapers and users who attempt to download or scrape way too much, but it shouldn't affect the actual download. If it does, I think it is either a browser or a Cloudflare issue, but one I haven't run into, even when we tested these captcha challenge pages.

I'm going to close this issue, but if someone else ever runs into it, please reopen with some more details. A sample of the downloaded APK that is actually HTML would be good.

**Closed by archon810** 2018-03-29 20:06 UTC

**Comment by m1st0** [comment] 2018-04-04 18:58
Here is the HTML as necessary, likely some issue with my browser or filtering, but for reference:
```
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Attention Required! | Cloudflare</title>

<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>


<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script><!--<![endif]-->
<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script><!--<![endif]-->




</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="challenge_headline">One more step</h1>
        <h2 class="cf-subheadline"><span data-translate="complete_sec_check">Please complete the security check to access</span> apkmirror.com</h2>
      </div><!-- /.header -->
      
      <div class="cf-section cf-highlight cf-captcha-container">
        <div class="cf-wrapper">
          <div class="cf-columns two">
            <div class="cf-column">
            
              <div class="cf-highlight-inverse cf-form-stacked">
                <form class="challenge-form" id="challenge-form" action="/wp-content/uploads/2017/08/598de4d0d6a26/com.southwestairlines.mobile_4.8.2-408020_minAPI21(nodpi)_apkmirror.com.apk?verify=1522867728-W7M1T3H4z6nBAmrRTRQeTs+sQSWPlKslQocr/5k0N1I=&amp;__cf_waf_tk__=117559002wEDu3qcPupsXgW95h8UfDpGz_gQ" method="post" enctype="application/x-www-form-urlencoded">
  <script type="text/javascript" src="/cdn-cgi/scripts/cf.challenge.js" data-type="normal"  data-ray="4065fb12bee439b8" async data-sitekey="6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0"></script>
  <div class="g-recaptcha"></div>
  <noscript id="cf-captcha-bookmark" class="cf-captcha-info">
    <div><div style="width: 302px">
      <div>
        <iframe src="https://www.google.com/recaptcha/api/fallback?k=6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0" frameborder="0" scrolling="no" style="width: 302px; height:422px; border-style: none;"></iframe>
      </div>
      <div style="width: 300px; border-style: none; bottom: 12px; left: 25px; margin: 0px; padding: 0px; right: 25px; background: #f9f9f9; border: 1px solid #c1c1c1; border-radius: 3px;">
        <textarea id="g-recaptcha-response" name="g-recaptcha-response" class="g-recaptcha-response" style="width: 250px; height: 40px; border: 1px solid #c1c1c1; margin: 10px 25px; padding: 0px; resize: none;"></textarea>
        <input type="submit" value="Submit"></input>
      </div>
    </div></div>
  </noscript>
</form>

              </div>
            </div>

            <div class="cf-column">
              <div class="cf-screenshot-container">
              
                <span class="cf-no-screenshot"></span>
              
              </div>
            </div>
          </div><!-- /.columns -->
        </div>
      </div><!-- /.captcha-container -->

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="why_captcha_headline">Why do I have to complete a CAPTCHA?</h2>
            
            <p data-translate="why_captcha_detail">Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="resolve_captcha_headline">What can I do to prevent this in the future?</h2>
            

            <p data-translate="resolve_captcha_antivirus">If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.</p>

            <p data-translate="resolve_captcha_network">If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.</p>
            
          </div>
        </div>
      </div><!-- /.section -->
      

      <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>[REMOVED]</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Your IP</span>: [REMOVED]</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
    
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item">
      <select id="lang-selector">
        <option value="">Select a Language</option>
        <option value="en">English</option>
        <option value="es">Español</option>
      </select>
    </span>
    
  </p>
</div><!-- /.error-footer -->


    </div><!-- /#cf-error-details -->
  </div><!-- /#cf-wrapper -->

  <script type="text/javascript">
  window._cf_translation = {};
  window._cf_translation.locale = 'en';
  window._cf_translation.blobs = {};
</script>

</body>
</html>

```
