### ISSUE TITLE
Auto inserted Google ads in release listings prevent info buttons from working

### ISSUE THREAD

**Issue by MihirGosai** [android-police/apkmirror-public#130] opened 2020-05-19 15:40 UTC
#### Expected behavior
All results should collapse on click of info(i) icon

#### Actual behavior
Unable to collapse 3rd search result (APK)
![Screenshot_20200519-211138_Chrome](https://user-images.githubusercontent.com/7599834/82347744-a4513e80-9a15-11ea-995b-a5b257e8b7ab.png)

#### Steps to reproduce the problem
Visit
https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s=My+talking

**Comment by archon810** [comment] 2020-05-19 15:45
I can't reproduce this. There may be an ad there or something that didn't load?

**Comment by MihirGosai** [comment] 2020-05-19 17:13
Okay. Something is wrong at second ad space only. I recorded video.

**Comment by archon810** [comment] 2020-05-19 17:16
OK, I just reproduced this in Chrome dev tools using mobile emulation.

Indeed, the info button above the auto inserted Google ad (thanks, Google!) doesn't do anything. @SeBsZ Can you reproduce and analyze please?

![image](https://user-images.githubusercontent.com/469543/82357242-aa193680-99b9-11ea-9a46-3bd93ec3d68c.png)

![image](https://user-images.githubusercontent.com/469543/82357234-a7b6dc80-99b9-11ea-908d-7ce0eb0ecc73.png)

**Comment by SeBsZ** [comment] 2020-05-21 13:08
@archon810 fixed in PR 1390

**Comment by archon810** [comment] 2020-05-21 17:00
Oh, so Google inserts itself in between our card and the hidden div that opens. This looks weird. Is it possible to group the two together so that Google doesn't insert things in between like that and only inserts in between cells?

![image](https://user-images.githubusercontent.com/469543/82584800-debbf800-9b49-11ea-90d0-c492e36d36c0.png)

**Comment by SeBsZ** [comment] 2020-05-22 13:05
@archon810 I created PR 1393 for you that surrounds each row with a div, can you give it a try? I'm not getting the ads on my machine so I can't test this logic.

**Comment by archon810** [comment] 2020-05-22 14:55
I'll test, thanks. Are you checking the search results page without an ad blocker? Because it only does it for me there, not the homepage lists because we already inject ads on those ourselves.

**Comment by archon810** [comment] 2020-05-22 19:03
We made a tweak to the page to see if it'd fix this case, but Google stopped serving auto ads, likely due to the fact that the structure changed. I'll check back in a few days/weeks to see if the ads came back.

**Comment by MihirGosai** [comment] 2020-05-27 09:48
Now, it's fixed.
![Screenshot_20200527-151730_Chrome](https://user-images.githubusercontent.com/7599834/83004457-52b83d80-a02d-11ea-90e1-3319af426e0c.png)

**Closed** 2020-05-27 09:49 UTC
Labels: bug
