### ISSUE TITLE
google chrome 5.0 feed not updated since a while ago

### ISSUE THREAD

**Issue by patrickdrd** [android-police/apkmirror-public#109] opened 2020-02-20 08:52 UTC
I'm referring to this feed:

[(http://www.apkmirror.com/apk/google-inc/chrome/variant-%7B%22minapi_slug%22%3A%22minapi-21%22%7D/feed/)]

**Comment by archon810** [comment] 2020-02-22 01:06
Thank you for reporting. I can reproduce the issue, we'll get on it ASAP.

**Comment by archon810** [comment] 2020-02-22 15:05
The fix has been rolled out.

**Closed by archon810** 2020-02-22 15:05 UTC
Labels: bug

**Comment by patrickdrd** [comment] 2020-02-25 09:18
5.0 releases are version 72?
why?
we're on version 80 already!

**Comment by archon810** [comment] 2020-02-25 14:55
It's because of https://www.androidpolice.com/2018/05/30/android-app-bundles-dynamic-delivery-will-change-way-phone-gets-software/.

A solution to support split apks is almost here though.

**Comment by patrickdrd** [comment] 2020-02-25 15:12
I see...
I like to keep a backup (.apk) of my apps,
will that be possible with that split apk format?
I mean is there any kind of conversion between apks and apk?

**Comment by archon810** [comment] 2020-02-25 22:26
Split APKs are just that - smaller APKs. Several of them are needed for the app to run.

What we'll be offering are single-file bundles of all the splits combined inside. You'll be able to archive that no problem.
