### ISSUE TITLE
Some apps are considered as multi variants even if they are not 

### ISSUE THREAD

**Issue by andyg21** [android-police/apkmirror-public#134] opened 2020-06-22 09:54 UTC
#### Expected behavior
If app is not multi variant, APK link should redirect to main page
For example
https://www.apkmirror.com/apk/chipotle-mexican-grill/chipotle/chipotle-8-4-5-release/
Should be redirected to
https://www.apkmirror.com/apk/chipotle-mexican-grill/chipotle/chipotle-8-4-5-release/chipotle-8-4-5-android-apk-download/

#### Actual behavior
When I visit home page and click on such apk posts, I need to visit one unnecessary page that shows list of variants. However only one universal variant exists.
For example, 
https://www.apkmirror.com/apk/chipotle-mexican-grill/chipotle/chipotle-8-4-5-release/

#### Steps to reproduce the problem
Go to
https://www.apkmirror.com/apk/chipotle-mexican-grill/chipotle/chipotle-8-4-5-release/

**Comment by archon810** [comment] 2020-06-23 00:15
Thanks for reporting. Dupe of https://github.com/android-police/apkmirror-public/issues/134.

**Closed by archon810** 2020-06-23 00:15 UTC

**Comment by andyg21** [comment] 2020-06-23 01:51
Dupe of #134? No, 134 is ID of this issue itself.

**Comment by archon810** [comment] 2020-06-23 03:11
Sorry, #51.
