### ISSUE TITLE
Change the proprietary .apkm format to open format

### ISSUE THREAD

**Issue by shah-sudeep** [android-police/apkmirror-public#144] opened 2020-08-16 01:28 UTC
First of all thanks for considering to make the .apkm format unencrypted format.
Now it's a humble request to make the format too open so that other apps to can support the Installation of .apkm files. Although we may install from other apps by renaming the format to zip or any other but that won't be the better way, Instead if you make that format open, those apps can easily handle the .apkm format without needing to rename to their supported format.

**Comment by archon810** [comment] 2020-09-05 05:54
Dupe of https://github.com/android-police/apkmirror-public/issues/119.

**Closed by archon810** 2020-09-05 05:54 UTC
